project:
  type: website
  render:
    - index.qmd
    - resources.qmd

website:
  title: 'Fullstack Academy AI/ML cohort 2605'
  navbar:
    left:
      - text: 'Home'
        href: index.qmd
      - text: 'Resources'
        href: resources.qmd
    right:
      - icon: github
        href: https://github.com/gperdrizet/fullstack-2605
        aria-label: GitHub

format:
  html:
    theme: cosmo
